Development
sqrtroot/toolchain pull request #1
Opened 2017-05-23 10:44 UTC by kasumi-owari

Added stty command when flashing on linux to set the baudrate to 1200 so you don't have to do this manually anymore.

2017-05-23 15:56 UTC, sqrtroot requested changes
To reset the device this is needed but a better cross platform way would be nice.

2017-05-23 15:56 UTC, sqrtroot commented on targets/arm32/cm3/atmel/sam3x/sam3x8e/flashscripts/arduino_due.cmake
> +    if(MSYS OR MINGW)
What if i use other build systems like ninja on windows?
what was wrong with checking for win32?

2017-05-24 08:37 UTC, kasumi-owari commented on targets/arm32/cm3/atmel/sam3x/sam3x8e/flashscripts/arduino_due.cmake
> +    if(MSYS OR MINGW)
Checking for win32 checks the build target and since it's compiling for arduino win32 will never be defined.

2017-05-24 08:39 UTC, sqrtroot commented on targets/arm32/cm3/atmel/sam3x/sam3x8e/flashscripts/arduino_due.cmake
> +    if(MSYS OR MINGW)
dangit, well we need to find another cross platform way. I'll merge this for now to get things working. But any help finding a better cross platform way for windows users would be nice

2017-05-24 08:39 UTC, sqrtroot approved these changes

2017-05-24 08:40 UTC, merged

2019-11-18 10:02 UTC, xekon commented
I am on KDE and have installed from the latest tar, currently on Arduino IDE 1.8.10  under Ubuntu + KDE and I still have to manually issue:

`stty -F /dev/ttyACM0 speed 1200 cs8 -cstopb -parenb`

in order for my sketches to upload, any idea what  the problem might be?